### PR TITLE
Logo For ArtiGenius-AI

### LINKED ISSUE #6: Design a unique logo for the app
## Custom Issue 🚀

**Description:**

The logo for the text-to-image generation app should capture the essence of transformation, creativity, and technology. Here's a unique concept for your app's logo.

1. Symbol: Combine a stylized letter "A" (representing text) with a pixelated brushstroke or digital pen nib. This fusion symbolizes the conversion of text into visual art.

2. Color Palette: Use vibrant and modern colors. Consider a gradient that starts with deep blue or purple representing the depth of text and transitions into lively shades of green or orange, representing creativity and innovation.

3. Typography: Choose a sleek and modern font for the app's name beneath the symbol. Make sure it's easily readable even in smaller sizes.

**Checklist (if applicable) ✅:**

- [ ] I have searched the issues to ensure a similar request or issue has not been submitted before.
- [ ] I have provided all the necessary details.

### PR DESCRIPTION
**Pull request by pranavdasan**
Made a logo for this repo/project, hope you like it!

* Fixes #6

### CODE REVIEW

**Review by ayuugoyal — CHANGES_REQUESTED** [review]
It's pretty good can you send some more color options in it??

**Comment by pranavdasan** [comment]
Sure, do you have any color options in mind, or do you want to me to make a variety of color combos

**Comment by ayuugoyal** [comment]
use something in black

**Comment by pranavdasan** [comment]
Added two, tell me what you think

**Pull request closed without merging**
