### PR TITLE
Implemented dark and light mode feature

### PR DESCRIPTION
**Pull request by Ajay-308**

### CODE REVIEW

**Review by Adi-ty — CHANGES_REQUESTED** [review]
Initially icon of moon is not correct 
image
image

The icon in dark mode should always be same.

**Comment by Ajay-308** [comment]
> Initially icon of moon is not correct image image
> 
> The icon in dark mode should always be same.

now its done you can check it

**Review by ayuugoyal — APPROVED** [review]
Looks Good

**Review by Adi-ty — COMMENTED** [review]
Issue still exists for first time when the theme is not set in local storage initially.

image

image

**Comment by Ajay-308** [comment]
Corrected this issue @Adi-ty wait let me check again

**Review by Adi-ty — APPROVED** [review]
LGTM, Thanks for contributing

**Pull request merged**
